import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/contexts/AuthProvider";
import ClientWrapper from "./ClientWrapper";
import { ConversationProvider } from "@/components/contexts/ConversationContext";
import { use } from "react";
import { useOnlineStatus } from "@/hooks/useOnlineStatus";
import OnlineStatusProvider from "@/components/contexts/OnlineStatusProvider";

const overpass = Overpass({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <AuthProvider>
          <ConversationProvider>
            <ClientWrapper>
              <OnlineStatusProvider>{children}</OnlineStatusProvider>
            </ClientWrapper>
          </ConversationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
