import type { Metadata } from "next";
import { Jost, Cabin, Overpass } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ChatBotAI from "./chatbot/ChatBotAI";
import { AuthProvider } from "@/components/contexts/AuthProvider";

const overpass = Overpass({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <AuthProvider>
          {children}
          <ChatBotAI />
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
