import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/contexts/AuthProvider";
import ClientWrapper from "./ClientWrapper";

const overpass = Overpass({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <AuthProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
